services:
  - type: web
    name: dating-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    branch: main
    envVars:
      - key: PORT
        value: 10000
